export const FETCH_QUIZES_START = 'FETCH_QUIZES_START'
export const FETCH_QUIZES_SUCCESS = 'FETCH_QUIZES_SUCCESS'
export const FETCH_QUIZES_ERRORS = 'FETCH_QUIZES_ERRORS'
export const FETCH_QUIZ_SUCCESS = 'FETCH_QUIZ_SUCCESS'